services:
  backend:
    build:
      context: ./backend
    container_name: research_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always
    environment:
      - PYTHONUNBUFFERED=1 # Ensures logs appear immediately
    command: python -m uvicorn app.main:app --reload # Assuming you're using FastAPI or similar
    # Alternatively, use flask or django commands if applicable
    # command: flask run --host=0.0.0.0

  frontend:
    build:
      context: ./frontend
    container_name: research_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: always
